-- CreateTable
CREATE TABLE "ClientIntake" (
    "id" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "company" TEXT NOT NULL,
    "website" TEXT,
    "projectType" TEXT NOT NULL,
    "projectDescription" TEXT NOT NULL,
    "goals" TEXT NOT NULL,
    "targetAudience" TEXT NOT NULL,
    "features" TEXT[],
    "designPreferences" TEXT,
    "brandGuidelines" TEXT,
    "contentReady" TEXT NOT NULL,
    "timeline" TEXT NOT NULL,
    "launchDate" TIMESTAMP(3),
    "budget" TEXT NOT NULL,
    "competitors" TEXT,
    "inspiration" TEXT,
    "additionalNotes" TEXT,
    "preferredCallDate" TEXT,
    "preferredCallTime" TEXT,
    "uploadedFiles" TEXT[],
    "termsAccepted" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "depositPaid" BOOLEAN NOT NULL DEFAULT false,
    "depositAmount" INTEGER,
    "finalPaymentPaid" BOOLEAN NOT NULL DEFAULT false,
    "stripeSessionId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ClientIntake_pkey" PRIMARY KEY ("id")
);
